1- Get total sales revenue

SELECT SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE FROM ORDERS;

2- Get top 5 best selling PRODUCTS

SELECT P.NAME, SUM(OD.QUANTITY) AS TOTAL_SOLD
FROM ORDER_DETAILS OD 
JOIN PRODUCTS P ON OD.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.NAME
ORDER BY TOTAL_SOLD DESC
LIMIT 5;

3- Get top 5 customers by spending

SELECT C.NAME, SUM(O.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM CUSTOMERS C
JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.NAME
ORDER BY TOTAL_SPENT DESC
LIMIT 5;

4- Get monthly sales

SELECT DATE_FORMAT (ORDER_DATE, '%Y-%M') AS MONTH, SUM (TOTAL_AMOUNT) AS MONTHLY_SALES
FROM ORDERS
GROUP BY MONTH
ORDER BY MONTH;

