## CUSTOMERS TABLE
CREATE TABLE CUSTOMERS(
    CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR (100),
    EMAIL VARCHAR (100) UNIQUE,
    PHONE VARCHAR (15),
    LOCATION VARCHAR (100)
);


## PRODUCTS TABLE
CREATE TABLE PRODUCTS(
    PRODUCT_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR (100),
    CATEGORY VARCHAR (50),
    PRICE DECIMAL (10,2)
);


## ORDERS TABLE
CREATE TABLE ORDERS(
    ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT,
    ORDER_DATE DATE,
    TOTAL_AMOUNT DECIMAL (10,2)
    FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);


## ORDER_DETAILS TABLE
CREATE TABLE ORDER_DETAILS(
    ORDER_ID INT,
    PRODUCT_ID INT,
    QUANTITY INT,
    SUBTOTAL DECIMAL(10,2),
    PRIMARY KEY (ORDER_ID, PRODUCT_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);


